begin;

alter table public.staff_table_assignments
  add column if not exists id bigint generated by default as identity,
  add column if not exists invite_id text references public.guest_list(id) on delete cascade;

alter table public.staff_table_assignments
  drop constraint if exists staff_table_assignments_pkey;

alter table public.staff_table_assignments
  alter column rsvp_id drop not null,
  alter column id set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.staff_table_assignments'::regclass
      and conname = 'staff_table_assignments_id_pkey'
  ) then
    alter table public.staff_table_assignments
      add constraint staff_table_assignments_id_pkey primary key (id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.staff_table_assignments'::regclass
      and conname = 'staff_table_assignments_one_subject'
  ) then
    alter table public.staff_table_assignments
      add constraint staff_table_assignments_one_subject
      check (num_nonnulls(rsvp_id, invite_id) = 1);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.staff_table_assignments'::regclass
      and conname = 'staff_table_assignments_event_rsvp_key'
  ) then
    alter table public.staff_table_assignments
      add constraint staff_table_assignments_event_rsvp_key unique (event_key, rsvp_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.staff_table_assignments'::regclass
      and conname = 'staff_table_assignments_event_invite_key'
  ) then
    alter table public.staff_table_assignments
      add constraint staff_table_assignments_event_invite_key unique (event_key, invite_id);
  end if;
end
$$;

create or replace function public.sync_invite_table_assignment_to_rsvp()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'attending' then
    if exists (
      select 1
      from public.staff_table_assignments
      where event_key = new.event_key
        and rsvp_id = new.id
    ) then
      delete from public.staff_table_assignments
      where event_key = new.event_key
        and invite_id = new.guest_id;
    else
      update public.staff_table_assignments
      set rsvp_id = new.id,
          invite_id = null,
          assigned_at = now()
      where event_key = new.event_key
        and invite_id = new.guest_id;
    end if;
  elsif new.status = 'declined' then
    delete from public.staff_table_assignments
    where event_key = new.event_key
      and (
        rsvp_id = new.id
        or invite_id = new.guest_id
      );
  end if;

  return new;
end
$$;

drop trigger if exists rsvps_sync_invite_table_assignment on public.rsvps;
create trigger rsvps_sync_invite_table_assignment
after insert or update of status, guest_id on public.rsvps
for each row execute function public.sync_invite_table_assignment_to_rsvp();

notify pgrst, 'reload schema';

commit;
