create table if not exists guest_list (
  id text primary key,
  name text not null,
  email text,
  created_at timestamptz default now()
);

create table if not exists rsvps (
  id bigint generated by default as identity primary key,
  event_key text not null,
  guest_id text not null,
  guest_name text not null,
  status text not null check (status in ('attending','declined')),
  plus_one_name text,
  plus_one_email text,
  seal_code text,
  ticket_token text,
  checked_in_at timestamptz,
  plus_one_ticket_token text,
  plus_one_seal_code text,
  plus_one_checked_in_at timestamptz,
  submitted_at timestamptz default now(),
  unique(event_key, guest_id)
);

create index if not exists guest_list_name_idx on guest_list using gin (to_tsvector('simple', name));
create unique index if not exists rsvps_event_plus_one_email_unique
  on rsvps (event_key, lower(plus_one_email))
  where plus_one_email is not null;
create unique index if not exists rsvps_event_seal_code_unique
  on rsvps (event_key, seal_code)
  where seal_code is not null;
create unique index if not exists rsvps_ticket_token_unique
  on rsvps (ticket_token)
  where ticket_token is not null;
create index if not exists rsvps_checked_in_at_idx on rsvps (checked_in_at);
create unique index if not exists rsvps_plus_one_ticket_token_unique
  on rsvps (plus_one_ticket_token)
  where plus_one_ticket_token is not null;
create unique index if not exists rsvps_event_plus_one_seal_code_unique
  on rsvps (event_key, plus_one_seal_code)
  where plus_one_seal_code is not null;

create table if not exists event_details (
  event_key text primary key,
  venue_name text,
  venue_address text,
  map_url text,
  reveal_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table event_details enable row level security;
insert into event_details (event_key, reveal_at)
values ('whispers-2026-10-10', '2026-10-09 18:00:00+03')
on conflict (event_key) do nothing;

insert into guest_list (id, name, email) values
  ('demo-peter-popov', 'Peter Popov', null),
  ('demo-simona-ivanova', 'Simona Ivanova', null),
  ('demo-maria-nikolova', 'Maria Nikolova', null),
  ('demo-georgi-petrov', 'Georgi Petrov', null),
  ('demo-alex-stoyanov', 'Alex Stoyanov', null)
on conflict (id) do nothing;
