create table if not exists guest_list (
  id text primary key,
  name text not null,
  email text,
  phone text,
  ticket_token text,
  confirmation_email_sent_at timestamptz,
  confirmation_email_send_count integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz not null default now()
);

create table if not exists rsvps (
  id bigint generated by default as identity primary key,
  event_key text not null,
  guest_id text not null,
  guest_name text not null,
  guest_email text,
  guest_phone text,
  status text not null check (status in ('attending','declined')),
  plus_one_name text,
  plus_one_email text,
  plus_one_phone text,
  plus_one_email_is_fallback boolean not null default false,
  wants_table_reservation boolean not null default false,
  reservation_confirmed boolean not null default false,
  seal_code text,
  confirmation_token text,
  ticket_token text,
  checked_in_at timestamptz,
  plus_one_ticket_token text,
  plus_one_seal_code text,
  plus_one_checked_in_at timestamptz,
  ticket_email_sent_at timestamptz,
  submitted_at timestamptz default now(),
  unique(event_key, guest_id)
);

create index if not exists guest_list_name_idx on guest_list using gin (to_tsvector('simple', name));
create unique index if not exists guest_list_ticket_token_unique
  on guest_list (ticket_token)
  where ticket_token is not null;
create unique index if not exists rsvps_event_plus_one_email_unique
  on rsvps (event_key, lower(plus_one_email))
  where plus_one_email is not null;
create unique index if not exists rsvps_event_seal_code_unique
  on rsvps (event_key, seal_code)
  where seal_code is not null;
create unique index if not exists rsvps_ticket_token_unique
  on rsvps (ticket_token)
  where ticket_token is not null;
create unique index if not exists rsvps_confirmation_token_unique
  on rsvps (confirmation_token)
  where confirmation_token is not null;
create index if not exists rsvps_checked_in_at_idx on rsvps (checked_in_at);
create index if not exists rsvps_contact_lookup_idx
  on rsvps (event_key, guest_email, guest_phone)
  where guest_email is not null and guest_phone is not null;
create index if not exists rsvps_ticket_email_pending_idx
  on rsvps (event_key, ticket_email_sent_at)
  where status = 'attending' and ticket_token is not null;
create unique index if not exists rsvps_plus_one_ticket_token_unique
  on rsvps (plus_one_ticket_token)
  where plus_one_ticket_token is not null;
create unique index if not exists rsvps_event_plus_one_seal_code_unique
  on rsvps (event_key, plus_one_seal_code)
  where plus_one_seal_code is not null;

create table if not exists rsvp_companions (
  id bigint generated by default as identity primary key,
  rsvp_id bigint not null references public.rsvps(id) on delete cascade,
  guest_name text not null,
  email text,
  email_is_fallback boolean not null default false,
  phone text not null,
  confirmation_token text,
  ticket_token text,
  seal_code text,
  checked_in_at timestamptz,
  ticket_email_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists rsvp_companions_ticket_token_unique
  on rsvp_companions (ticket_token)
  where ticket_token is not null;
create unique index if not exists rsvp_companions_confirmation_token_unique
  on rsvp_companions (confirmation_token)
  where confirmation_token is not null;
create unique index if not exists rsvp_companions_seal_code_unique
  on rsvp_companions (seal_code)
  where seal_code is not null;
create index if not exists rsvp_companions_email_pending_idx
  on rsvp_companions (ticket_email_sent_at)
  where ticket_token is not null;
alter table rsvp_companions enable row level security;

create table if not exists event_details (
  event_key text primary key,
  venue_name text,
  venue_address text,
  map_url text,
  reveal_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table event_details enable row level security;
insert into event_details (event_key, reveal_at)
values ('whispers-2026-10-10', '2026-10-09 18:00:00+03')
on conflict (event_key) do nothing;

create table if not exists staff_tables (
  id text primary key,
  label text not null,
  minimum_spend_eur integer not null default 0 check (minimum_spend_eur >= 0),
  map_x numeric(5,2) not null default 50 check (map_x between 0 and 100),
  map_y numeric(5,2) not null default 50 check (map_y between 0 and 100),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table staff_tables enable row level security;

create table if not exists staff_table_assignments (
  event_key text not null,
  rsvp_id bigint not null references public.rsvps(id) on delete cascade,
  table_id text not null references public.staff_tables(id) on delete cascade,
  assigned_at timestamptz not null default now(),
  primary key (event_key, rsvp_id)
);
alter table staff_table_assignments enable row level security;

create table if not exists staff_users (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  password_hash text not null,
  role text not null check (role in ('owner', 'admin', 'door', 'service')),
  active boolean not null default true,
  failed_login_count integer not null default 0,
  locked_until timestamptz,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists staff_users_username_unique
  on staff_users (lower(username));
alter table staff_users enable row level security;

create table if not exists staff_sessions (
  id uuid primary key default gen_random_uuid(),
  staff_user_id uuid not null references public.staff_users(id) on delete cascade,
  session_token_hash text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz
);
create unique index if not exists staff_sessions_token_hash_unique
  on staff_sessions (session_token_hash);
create index if not exists staff_sessions_user_idx
  on staff_sessions (staff_user_id);
create index if not exists staff_sessions_expires_idx
  on staff_sessions (expires_at);
alter table staff_sessions enable row level security;

insert into staff_tables (id, label, sort_order, map_x, map_y) values
  ('t1', 'Table 1', 1, 10, 7),
  ('t2', 'Table 2', 2, 30, 7),
  ('t3', 'Table 3', 3, 50, 7),
  ('t4', 'Table 4', 4, 70, 7),
  ('t5', 'Table 5', 5, 90, 7),
  ('t6', 'Table 6', 6, 10, 21),
  ('t7', 'Table 7', 7, 30, 21),
  ('t8', 'Table 8', 8, 50, 21),
  ('t9', 'Table 9', 9, 70, 21),
  ('t10', 'Table 10', 10, 90, 21),
  ('t11', 'Table 11', 11, 10, 35),
  ('t12', 'Table 12', 12, 30, 35),
  ('t13', 'Table 13', 13, 50, 35),
  ('t14', 'Table 14', 14, 70, 35),
  ('t15', 'Table 15', 15, 90, 35),
  ('t16', 'Table 16', 16, 10, 49),
  ('t17', 'Table 17', 17, 30, 49),
  ('t18', 'Table 18', 18, 50, 49),
  ('t19', 'Table 19', 19, 70, 49),
  ('t20', 'Table 20', 20, 90, 49),
  ('t21', 'Table 21', 21, 10, 63),
  ('t22', 'Table 22', 22, 30, 63),
  ('t23', 'Table 23', 23, 50, 63),
  ('t24', 'Table 24', 24, 70, 63),
  ('t25', 'Table 25', 25, 90, 63),
  ('t26', 'Table 26', 26, 10, 77),
  ('t27', 'Table 27', 27, 30, 77),
  ('t28', 'Table 28', 28, 50, 77),
  ('t29', 'Table 29', 29, 70, 77),
  ('t30', 'Table 30', 30, 90, 77),
  ('t31', 'Table 31', 31, 10, 91),
  ('t32', 'Table 32', 32, 30, 91),
  ('t33', 'Table 33', 33, 50, 91),
  ('t34', 'Table 34', 34, 70, 91),
  ('t35', 'Table 35', 35, 90, 91)
on conflict (id) do nothing;

insert into guest_list (id, name, email) values
  ('demo-peter-popov', 'Peter Popov', null),
  ('demo-simona-ivanova', 'Simona Ivanova', null),
  ('demo-maria-nikolova', 'Maria Nikolova', null),
  ('demo-georgi-petrov', 'Georgi Petrov', null),
  ('demo-alex-stoyanov', 'Alex Stoyanov', null)
on conflict (id) do nothing;

update guest_list
set ticket_token = replace(gen_random_uuid()::text, '-', ''),
    updated_at = now()
where ticket_token is null;
